app:
  port: 3001
  resource:
    region: "ap-northeast-2"
    bucket: "bucket"
    address: resource.example.com
  serviceName: service
  serviceUrl: http://localhost:3000
  systemEMailAddress: noreply@example.com
  jwtSecret: secret

db:
  allowSync: false
  
user:
  operator:
    - username: admin
      password: admin
      email: dummy@dummy.com
      name: admin

client:
  - name: "clients"
    clientId: "client"
    clientSecret: "somesecret"
    scope: operator
    grants: ["password", "refresh_token"]
    redirectUris: ["http://localhost:3000/redirect"]
    accessTokenLifetime: 3600
    refreshTokenLifetime: 7200


swagger:
  enable: true
  urls:
    - url: http://localhost:3001
      name: local

NODE_ENV: development
